// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
  public partial class PrivateCancelAllRequest
  {
    /// <summary>
    /// <para>When detailed is set to <c>true</c> output format is changed. See <a href="https://docs.deribit.com/#detailed-response-for-private-cancel_all-and-private-cancel_by_label-methods">description</a>. Default: <c>false</c></para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("detailed")]
    public bool? Detailed { get; set; }
  }
}
