// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>The currency symbol or <c>&quot;any&quot;</c> for all</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
  public partial class CurrencySymbolOrAny : DeriSock.Model.EnumValue
  {
    public static CurrencySymbolOrAny BTC = new CurrencySymbolOrAny("BTC");
    public static CurrencySymbolOrAny ETH = new CurrencySymbolOrAny("ETH");
    public static CurrencySymbolOrAny SOL = new CurrencySymbolOrAny("SOL");
    public static CurrencySymbolOrAny USDC = new CurrencySymbolOrAny("USDC");
    public static CurrencySymbolOrAny Any = new CurrencySymbolOrAny("any");
    private CurrencySymbolOrAny(string value) : 
        base(value)
    {
    }
  }
}
