// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Index identifier supported for DVOL</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
  public partial class DeribitVolatilityIndexName : DeriSock.Model.EnumValue
  {
    public static DeribitVolatilityIndexName BtcUsd = new DeribitVolatilityIndexName("btc_usd");
    public static DeribitVolatilityIndexName EthUsd = new DeribitVolatilityIndexName("eth_usd");
    public static DeribitVolatilityIndexName SolUsd = new DeribitVolatilityIndexName("sol_usd");
    private DeribitVolatilityIndexName(string value) : 
        base(value)
    {
    }
  }
}
