// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Specifies time period. <c>8h</c> - 8 hours, <c>24h</c> - 24 hours, <c>1m</c> - 1 month</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
  public partial class FundingChartPeriod : DeriSock.Model.EnumValue
  {
    public static FundingChartPeriod _8h = new FundingChartPeriod("8h");
    public static FundingChartPeriod _24h = new FundingChartPeriod("24h");
    public static FundingChartPeriod _1m = new FundingChartPeriod("1m");
    private FundingChartPeriod(string value) : 
        base(value)
    {
    }
  }
}
