// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Index identifier, matches (base) cryptocurrency with quote currency</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
  public partial class IndexName : DeriSock.Model.EnumValue
  {
    public static IndexName AdaUsd = new IndexName("ada_usd");
    public static IndexName AvaxUsd = new IndexName("avax_usd");
    public static IndexName BtcUsd = new IndexName("btc_usd");
    public static IndexName EthUsd = new IndexName("eth_usd");
    public static IndexName DotUsd = new IndexName("dot_usd");
    public static IndexName LunaUsd = new IndexName("luna_usd");
    public static IndexName MaticUsd = new IndexName("matic_usd");
    public static IndexName SolUsd = new IndexName("sol_usd");
    public static IndexName UsdcUsd = new IndexName("usdc_usd");
    public static IndexName XrpUsd = new IndexName("xrp_usd");
    public static IndexName AdaUsdc = new IndexName("ada_usdc");
    public static IndexName AvaxUsdc = new IndexName("avax_usdc");
    public static IndexName BtcUsdc = new IndexName("btc_usdc");
    public static IndexName EthUsdc = new IndexName("eth_usdc");
    public static IndexName DotUsdc = new IndexName("dot_usdc");
    public static IndexName LunaUsdc = new IndexName("luna_usdc");
    public static IndexName MaticUsdc = new IndexName("matic_usdc");
    public static IndexName SolUsdc = new IndexName("sol_usdc");
    public static IndexName XrpUsdc = new IndexName("xrp_usdc");
    public static IndexName BtcdvolUsdc = new IndexName("btcdvol_usdc");
    public static IndexName EthdvolUsdc = new IndexName("ethdvol_usdc");
    private IndexName(string value) : 
        base(value)
    {
    }
  }
}
