// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Kind filter on positions</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
  public partial class InstrumentKind : DeriSock.Model.EnumValue
  {
    public static InstrumentKind Future = new InstrumentKind("future");
    public static InstrumentKind Option = new InstrumentKind("option");
    private InstrumentKind(string value) : 
        base(value)
    {
    }
  }
}
