// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>enable or disable login.</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
  public partial class LoginStatus : DeriSock.Model.EnumValue
  {
    public static LoginStatus Enable = new LoginStatus("enable");
    public static LoginStatus Disable = new LoginStatus("disable");
    private LoginStatus(string value) : 
        base(value)
    {
    }
  }
}
