// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Frequency of notifications. Events will be aggregated over this interval.</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
  public partial class NotificationInterval1 : DeriSock.Model.EnumValue
  {
    public static NotificationInterval1 _100ms = new NotificationInterval1("100ms");
    private NotificationInterval1(string value) : 
        base(value)
    {
    }
  }
}
