// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Number of price levels to be included.</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
  public partial class PriceLevelDepth : DeriSock.Model.EnumValue
  {
    public static PriceLevelDepth _1 = new PriceLevelDepth("1");
    public static PriceLevelDepth _10 = new PriceLevelDepth("10");
    public static PriceLevelDepth _20 = new PriceLevelDepth("20");
    private PriceLevelDepth(string value) : 
        base(value)
    {
    }
  }
}
