// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Group prices (by rounding). Use <c>none</c> for no grouping.<br/>
  ///For ETH cryptocurrency, real <c>group</c> is divided by 100.0, e.g. given value <c>5</c> means using <c>0.05</c><br/>
  ///Allowed values for BTC - <c>none</c>, <c>1</c>, <c>2</c>, <c>5</c>, <c>10</c><br/>
  ///Allowed values for ETH - <c>none</c>, <c>5</c>, <c>10</c>, <c>25</c>, <c>100</c>, <c>250</c></para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
  public partial class PriceGrouping : DeriSock.Model.EnumValue
  {
    public static PriceGrouping None = new PriceGrouping("none");
    public static PriceGrouping _1 = new PriceGrouping("1");
    public static PriceGrouping _2 = new PriceGrouping("2");
    public static PriceGrouping _5 = new PriceGrouping("5");
    public static PriceGrouping _10 = new PriceGrouping("10");
    public static PriceGrouping _25 = new PriceGrouping("25");
    public static PriceGrouping _100 = new PriceGrouping("100");
    public static PriceGrouping _250 = new PriceGrouping("250");
    private PriceGrouping(string value) : 
        base(value)
    {
    }
  }
}
