// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Specifies how long the order remains in effect. Default <c>&quot;good_til_cancelled&quot;</c><br/>
  ///- <c>&quot;good_til_cancelled&quot;</c> - unfilled order remains in order book until cancelled<br/>
  ///- <c>&quot;good_til_day&quot;</c> - unfilled order remains in order book till the end of the trading session<br/>
  ///- <c>&quot;fill_or_kill&quot;</c> - execute a transaction immediately and completely or not at all<br/>
  ///- <c>&quot;immediate_or_cancel&quot;</c> - execute a transaction immediately, and any portion of the order that cannot be immediately filled is cancelled</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
  public partial class TimeInForce : DeriSock.Model.EnumValue
  {
    public static TimeInForce GoodTilCancelled = new TimeInForce("good_til_cancelled");
    public static TimeInForce GoodTilDay = new TimeInForce("good_til_day");
    public static TimeInForce FillOrKill = new TimeInForce("fill_or_kill");
    public static TimeInForce ImmediateOrCancel = new TimeInForce("immediate_or_cancel");
    private TimeInForce(string value) : 
        base(value)
    {
    }
  }
}
