// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Direction of trade from the maker perspective</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
  public partial class TradeDirection : DeriSock.Model.EnumValue
  {
    public static TradeDirection Buy = new TradeDirection("buy");
    public static TradeDirection Sell = new TradeDirection("sell");
    private TradeDirection(string value) : 
        base(value)
    {
    }
  }
}
