// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Defines the trigger type. Required for <c>&quot;Stop-Loss&quot;</c>, <c>&quot;Take-Profit&quot;</c> and <c>&quot;Trailing&quot;</c> trigger orders</para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
  public partial class TriggerType : DeriSock.Model.EnumValue
  {
    public static TriggerType IndexPrice = new TriggerType("index_price");
    public static TriggerType MarkPrice = new TriggerType("mark_price");
    public static TriggerType LastPrice = new TriggerType("last_price");
    private TriggerType(string value) : 
        base(value)
    {
    }
  }
}
