// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// <para>Withdrawal priority, optional for BTC, default: <c>high</c></para>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
  public partial class WithdrawPriority : DeriSock.Model.EnumValue
  {
    public static WithdrawPriority Insane = new WithdrawPriority("insane");
    public static WithdrawPriority ExtremeHigh = new WithdrawPriority("extreme_high");
    public static WithdrawPriority VeryHigh = new WithdrawPriority("very_high");
    public static WithdrawPriority High = new WithdrawPriority("high");
    public static WithdrawPriority Mid = new WithdrawPriority("mid");
    public static WithdrawPriority Low = new WithdrawPriority("low");
    public static WithdrawPriority VeryLow = new WithdrawPriority("very_low");
    private WithdrawPriority(string value) : 
        base(value)
    {
    }
  }
}
