// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock
{
  using System;
  using System.Threading;
  using System.Threading.Tasks;
  using DeriSock.Api;
  using DeriSock.Net.JsonRpc;
  using DeriSock.Model;
  using Newtonsoft.Json.Linq;
  
  public partial class DeribitClient
  {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
    private sealed partial class BlockTradeApiImpl : IBlockTradeApi
    {
      private readonly DeribitClient _client;
      public BlockTradeApiImpl(DeribitClient client)
      {
        _client = client;
      }
      /// <inheritdoc cref="IBlockTradeApi.PrivateExecuteBlockTrade" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<BlockTrade>> IBlockTradeApi.PrivateExecuteBlockTrade(PrivateExecuteBlockTradeRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPrivateExecuteBlockTrade(args, cancellationToken);
      }
      /// <inheritdoc cref="IBlockTradeApi.PrivateGetBlockTrade" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<BlockTrade>> IBlockTradeApi.PrivateGetBlockTrade(PrivateGetBlockTradeRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPrivateGetBlockTrade(args, cancellationToken);
      }
      /// <inheritdoc cref="IBlockTradeApi.PrivateGetLastBlockTradesByCurrency" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<BlockTrade[]>> IBlockTradeApi.PrivateGetLastBlockTradesByCurrency(PrivateGetLastBlockTradesByCurrencyRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPrivateGetLastBlockTradesByCurrency(args, cancellationToken);
      }
      /// <inheritdoc cref="IBlockTradeApi.PrivateInvalidateBlockTradeSignature" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<string>> IBlockTradeApi.PrivateInvalidateBlockTradeSignature(PrivateInvalidateBlockTradeSignatureRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPrivateInvalidateBlockTradeSignature(args, cancellationToken);
      }
      /// <inheritdoc cref="IBlockTradeApi.PrivateMovePositions" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<MovePositionResponse>> IBlockTradeApi.PrivateMovePositions(PrivateMovePositionsRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPrivateMovePositions(args, cancellationToken);
      }
      /// <inheritdoc cref="IBlockTradeApi.PrivateVerifyBlockTrade" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<VerifyBlockTradeResponse>> IBlockTradeApi.PrivateVerifyBlockTrade(PrivateVerifyBlockTradeRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPrivateVerifyBlockTrade(args, cancellationToken);
      }
    }
  }
}
