// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock
{
  using System;
  using System.Threading;
  using System.Threading.Tasks;
  using DeriSock.Api;
  using DeriSock.JsonRpc;
  using DeriSock.Model;
  using Newtonsoft.Json.Linq;
  
  public partial class DeribitClient
  {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
    private sealed partial class ComboBooksApiImpl : IComboBooksApi
    {
      private readonly DeribitClient _client;
      public ComboBooksApiImpl(DeribitClient client)
      {
        _client = client;
      }
      /// <inheritdoc cref="IComboBooksApi.PublicGetComboDetails" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
      System.Threading.Tasks.Task<DeriSock.JsonRpc.JsonRpcResponse<Combo>> IComboBooksApi.PublicGetComboDetails(PublicGetComboDetailsRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPublicGetComboDetails(args, cancellationToken);
      }
      /// <inheritdoc cref="IComboBooksApi.PublicGetComboIds" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
      System.Threading.Tasks.Task<DeriSock.JsonRpc.JsonRpcResponse<string[]>> IComboBooksApi.PublicGetComboIds(PublicGetComboIdsRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPublicGetComboIds(args, cancellationToken);
      }
      /// <inheritdoc cref="IComboBooksApi.PublicGetCombos" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
      System.Threading.Tasks.Task<DeriSock.JsonRpc.JsonRpcResponse<Combo[]>> IComboBooksApi.PublicGetCombos(PublicGetCombosRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPublicGetCombos(args, cancellationToken);
      }
      /// <inheritdoc cref="IComboBooksApi.PrivateCreateCombo" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
      System.Threading.Tasks.Task<DeriSock.JsonRpc.JsonRpcResponse<Combo>> IComboBooksApi.PrivateCreateCombo(PrivateCreateComboRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPrivateCreateCombo(args, cancellationToken);
      }
    }
  }
}
