// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock
{
  using System;
  using System.Threading;
  using System.Threading.Tasks;
  using DeriSock.Api;
  using DeriSock.Net.JsonRpc;
  using DeriSock.Model;
  using Newtonsoft.Json.Linq;
  
  public partial class DeribitClient
  {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
    private sealed partial class SessionManagementApiImpl : ISessionManagementApi
    {
      private readonly DeribitClient _client;
      public SessionManagementApiImpl(DeribitClient client)
      {
        _client = client;
      }
      /// <inheritdoc cref="ISessionManagementApi.PublicSetHeartbeat" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<string>> ISessionManagementApi.PublicSetHeartbeat(PublicSetHeartbeatRequest args, CancellationToken cancellationToken)
      {
        return _client.InternalPublicSetHeartbeat(args, cancellationToken);
      }
      /// <inheritdoc cref="ISessionManagementApi.PublicDisableHeartbeat" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<string>> ISessionManagementApi.PublicDisableHeartbeat(CancellationToken cancellationToken)
      {
        return _client.InternalPublicDisableHeartbeat(cancellationToken);
      }
      /// <inheritdoc cref="ISessionManagementApi.PrivateEnableCancelOnDisconnect" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<string>> ISessionManagementApi.PrivateEnableCancelOnDisconnect(PrivateEnableCancelOnDisconnectRequest? args, CancellationToken cancellationToken)
      {
        return _client.InternalPrivateEnableCancelOnDisconnect(args, cancellationToken);
      }
      /// <inheritdoc cref="ISessionManagementApi.PrivateDisableCancelOnDisconnect" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<string>> ISessionManagementApi.PrivateDisableCancelOnDisconnect(PrivateDisableCancelOnDisconnectRequest? args, CancellationToken cancellationToken)
      {
        return _client.InternalPrivateDisableCancelOnDisconnect(args, cancellationToken);
      }
      /// <inheritdoc cref="ISessionManagementApi.PrivateGetCancelOnDisconnect" />
      [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
      System.Threading.Tasks.Task<DeriSock.Net.JsonRpc.JsonRpcResponse<CancelOnDisconnectData>> ISessionManagementApi.PrivateGetCancelOnDisconnect(PrivateGetCancelOnDisconnectRequest? args, CancellationToken cancellationToken)
      {
        return _client.InternalPrivateGetCancelOnDisconnect(args, cancellationToken);
      }
    }
  }
}
