// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  using System;
  using DeriSock.Converter;
  
  /// <summary>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
  public partial class AccessLogEntry
  {
    /// <summary>
    /// <para>City where the IP address is registered (estimated)</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("city")]
    public string City { get; set; } = string.Empty;
    /// <summary>
    /// <para>Country where the IP address is registered (estimated)</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("country")]
    public string Country { get; set; } = string.Empty;
    /// <summary>
    /// <para>Optional, additional information about action, type depends on <c>log</c> value</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("data")]
    public DeriSock.Model.ObjectOrStringItem? Data { get; set; }
    /// <summary>
    /// <para>Unique identifier</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("id")]
    public int Id { get; set; }
    /// <summary>
    /// <para>IP address of source that generated action</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("ip")]
    public string Ip { get; set; } = string.Empty;
    /// <summary>
    /// <para>Action description, values: <c>changed_email</c> - email was changed; <c>changed_password</c> - password was changed; <c>disabled_tfa</c> - TFA was disabled; <c>enabled_tfa</c> - TFA was enabled, <c>success</c> - successful login; <c>failure</c> - login failure; <c>enabled_subaccount_login</c> - login was enabled for subaccount (in <c>data</c> - subaccount uid); <c>disabled_subaccount_login</c> - login was disabled for subbaccount (in <c>data</c> - subbacount uid);<c>new_api_key</c> - API key was created (in <c>data</c> key client id); <c>removed_api_key</c> - API key was removed (in <c>data</c> key client id); <c>changed_scope</c> - scope of API key was changed (in <c>data</c> key client id); <c>changed_whitelist</c> - whitelist of API key was edited (in <c>data</c> key client id); <c>disabled_api_key</c> - API key was disabled (in <c>data</c> key client id); <c>enabled_api_key</c> - API key was enabled (in <c>data</c> key client id); <c>reset_api_key</c> - API key was reset (in <c>data</c> key client id)</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("log")]
    public string Log { get; set; } = string.Empty;
    /// <summary>
    /// <para>The timestamp (milliseconds since the Unix epoch)</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("timestamp")]
    [Newtonsoft.Json.JsonConverter(typeof(MillisecondsTimestampConverter))]
    public DateTime Timestamp { get; set; }
  }
}
