// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
  public partial class AggregatedTradeVolume
  {
    /// <summary>
    /// <para>Total 24h trade volume for call options.</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("calls_volume")]
    public decimal CallsVolume { get; set; }
    /// <summary>
    /// <para>Total 30d trade volume for call options.</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("calls_volume_30d")]
    public decimal CallsVolume30D { get; set; }
    /// <summary>
    /// <para>Total 7d trade volume for call options.</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("calls_volume_7d")]
    public decimal CallsVolume7D { get; set; }
    /// <summary>
    /// <para>Currency, i.e <c>&quot;BTC&quot;</c>, <c>&quot;ETH&quot;</c>, <c>&quot;USDC&quot;</c></para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("currency")]
    public string Currency { get; set; } = string.Empty;
    /// <summary>
    /// <para>Total 24h trade volume for futures.</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("futures_volume")]
    public decimal FuturesVolume { get; set; }
    /// <summary>
    /// <para>Total 30d trade volume for futures.</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("futures_volume_30d")]
    public decimal FuturesVolume30D { get; set; }
    /// <summary>
    /// <para>Total 7d trade volume for futures.</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("futures_volume_7d")]
    public decimal FuturesVolume7D { get; set; }
    /// <summary>
    /// <para>Total 24h trade volume for put options.</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("puts_volume")]
    public decimal PutsVolume { get; set; }
    /// <summary>
    /// <para>Total 30d trade volume for put options.</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("puts_volume_30d")]
    public decimal PutsVolume30D { get; set; }
    /// <summary>
    /// <para>Total 7d trade volume for put options.</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("puts_volume_7d")]
    public decimal PutsVolume7D { get; set; }
  }
}
