// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  using System;
  using DeriSock.Converter;
  
  /// <summary>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "2.0.0")]
  public partial class AnnouncementChange
  {
    /// <summary>
    /// <para>Action taken by the platform administrators. Published a <c>new</c> announcement, or <c>delete</c>d the old one</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("action")]
    public string Action { get; set; } = string.Empty;
    /// <summary>
    /// <para>HTML-formatted announcement body</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("body")]
    public string Body { get; set; } = string.Empty;
    /// <summary>
    /// <para>Whether the user confirmation is required for this announcement</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("confirmation")]
    public bool Confirmation { get; set; }
    /// <summary>
    /// <para>Announcement&apos;s identifier</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("id")]
    public long Id { get; set; }
    /// <summary>
    /// <para>Whether the announcement is marked as important</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("important")]
    public bool Important { get; set; }
    /// <summary>
    /// <para>The timestamp (milliseconds since the Unix epoch) of announcement publication</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("publication_timestamp")]
    [Newtonsoft.Json.JsonConverter(typeof(MillisecondsTimestampConverter))]
    public DateTime PublicationTimestamp { get; set; }
    /// <summary>
    /// <para>Announcement&apos;s title</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("title")]
    public string Title { get; set; } = string.Empty;
    /// <summary>
    /// <para>The number of previous unread announcements (optional, only for authorized users).</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("unread")]
    public long? Unread { get; set; }
  }
}
