// --------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------
#pragma warning disable CS1591
#nullable enable
namespace DeriSock.Model
{
  
  /// <summary>
  /// </summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("DeriSock.DevTools", "0.3.5")]
  public partial class ExpirationPrice
  {
    /// <summary>
    /// <para>When <c>true</c> then price is given as an estimated value, otherwise it&apos;s current index price</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("is_estimated")]
    public bool IsEstimated { get; set; }
    /// <summary>
    /// <para>number of time ticks that are left until expiration (field added when price is estimated)</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("left_ticks")]
    public decimal LeftTicks { get; set; }
    /// <summary>
    /// <para>Index current or estimated price</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("price")]
    public decimal Price { get; set; }
    /// <summary>
    /// <para>Number of seconds till finalizing the nearest instrument</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("seconds")]
    public int Seconds { get; set; }
    /// <summary>
    /// <para>number of total time ticks (field added when price is estimated)</para>
    /// </summary>
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [Newtonsoft.Json.JsonPropertyAttribute("total_ticks")]
    public decimal TotalTicks { get; set; }
  }
}
