# reference: https://github.com/SingletonSean/wpf-mvvm-password-box/blob/master/.github/workflows/nuget.yml
# https://www.youtube.com/watch?v=cUrrdAVmo4I

name: "Deploy to NuGet"

on:
  push:
    tags:
      - v*

env:
  ContinuousIntegrationBuild: true
  PROJECT_PATH: src/DeriSock/DeriSock.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/dist
  NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      id: nuget-package-cache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nuget-

    - name: dotnet restore
      if: steps.nuget-package-cache.outputs.cache-hit != 'true'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: dotnet build
      run: dotnet build src/DeriSock --configuration Release

    - uses: battila7/get-version-action@v2
      id: version

    - name: dotnet pack
      run: dotnet pack src/DeriSock --no-restore --no-build --configuration Release
             --include-symbols
             -p:PackageVersion=${{ steps.version.outputs.version-without-v }}
             -p:RepositoryBranch=${{ github.ref_name }}
             -p:RepositoryCommit=${{ github.sha }}
             --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: dotnet nuget push
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_KEY }} -s ${{ env.NUGET_SOURCE_URL }}
