name: Build, Test and Publish DeriSock Project

on:
  workflow_dispatch:

jobs:
  build_test_publish:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Restore Packages
      run: |
        dotnet restore DeriSock
 #       dotnet restore DeriSock.Tests
        
    - name: Build with dotnet
      run: |
        dotnet build --no-restore --configuration Release DeriSock
#        dotnet build --no-restore --configuration Release DeriSock.Tests

#    - name: Run Tests
#      run: dotnet test --no-restore DeriSock.Tests

    - name: Create nuget package
      run: dotnet pack --configuration Release

    - name: Publish nuget package
      run: dotnet nuget push .\DeriSock\bin\Release\DeriSock.0.3.2.nupkg -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json